# include "TAttPad.h"
# include "TCanvas.h"
# include "TDirectory.h"
# include "TFile.h"
# include "TH1.h"
# include "TH2.h"
# include "TLegend.h"
# include "TLine.h"
# include "TPad.h"
# include "TPaveText.h"
# include "TProfile.h"
# include "TString.h"
# include "TStyle.h"
# include <fstream>
# include <iostream>

using namespace std;

TH2D * corr_HFm1_HFp1;
TH2D * corr_trackmid1_HFm1;
TH2D * corr_trackmid1_HFp1;
TH2D * corr_trackm1_HFm1;
TH2D * corr_trackm1_trackp1;
TH2D * corr_trackm1_HFp1;
TH2D * corr_trackp1_HFm1;
TH2D * corr_trackp1_trackm1;
TH2D * corr_trackp1_HFp1;

TH2D * corr_HFm1_trackm2;
TH2D * corr_HFm1_trackp2;
TH2D * corr_HFp1_trackm2;
TH2D * corr_HFp1_trackp2;
TH2D * corr_HFm1_HFp2;
TH2D * corr_HFp1_HFm2;
TH2D * corr_trackmid1_HFm2;
TH2D * corr_trackmid1_HFp2;
TH2D * corr_trackm1_HFm2;
TH2D * corr_trackm1_trackp2;
TH2D * corr_trackm1_HFp2;
TH2D * corr_trackp1_HFm2;
TH2D * corr_trackp1_trackm2;
TH2D * corr_trackp1_HFp2;

TH2D * corr_HFm2_HFp2;
TH2D * corr_trackmid2_HFm2;
TH2D * corr_trackmid2_HFp2;
TH2D * corr_trackm2_HFm2;
TH2D * corr_trackm2_trackp2;
TH2D * corr_trackm2_HFp2;
TH2D * corr_trackp2_HFm2;
TH2D * corr_trackp2_HFp2;


TH1D * cos_HFm1_HFp1;
TH1D * cos_trackmid1_HFm1;
TH1D * cos_trackmid1_HFp1;
TH1D * cos_trackm1_HFm1;
TH1D * cos_trackm1_trackp1;
TH1D * cos_trackm1_HFp1;
TH1D * cos_trackp1_HFm1;
TH1D * cos_trackp1_trackm1;
TH1D * cos_trackp1_HFp1;

TH1D * cos_HFm1_trackm2;
TH1D * cos_HFm1_trackp2;
TH1D * cos_HFp1_trackm2;
TH1D * cos_HFp1_trackp2;
TH1D * cos_HFm1_HFp2;
TH1D * cos_HFp1_HFm2;
TH1D * cos_trackmid1_HFm2;
TH1D * cos_trackmid1_HFp2;
TH1D * cos_trackm1_HFm2;
TH1D * cos_trackm1_trackp2;
TH1D * cos_trackm1_HFp2;
TH1D * cos_trackp1_HFm2;
TH1D * cos_trackp1_trackm2;
TH1D * cos_trackp1_HFp2;

TH1D * cos_HFm2_HFp2;
TH1D * cos_trackmid2_HFm2;
TH1D * cos_trackmid2_HFp2;
TH1D * cos_trackm2_HFm2;
TH1D * cos_trackm2_trackp2;
TH1D * cos_trackm2_HFp2;
TH1D * cos_trackp2_HFm2;
TH1D * cos_trackp2_HFp2;

TFile * tfin;

TDirectory * tdEPcorr;
TDirectory * tdEPcos;

void EPplot( TString infile )
{
    if (!fopen("plots","r")) system("mkdir plots");

    tfin = new TFile(Form("%s",infile.Data()));
    if (infile.Contains("eta_weights")) eta_weights = kTRUE;
    if (infile.Contains("even")) iseven = kTRUE;
    if (infile.Contains("odd")) isodd = kTRUE;
    if (infile.Contains("0.0000")) iszero = kTRUE;
    if (infile.Contains("pt_weights")) pt_weights = kTRUE;
    if (infile.Contains("mon-cons")) conserve_pT = kTRUE; // change later "mom-cons"
    if (infile.Contains("hole")) ishole = kTRUE;
    if (infile.Contains("recenter")) recentered = kTRUE;

    tdEPcorr = (TDirectory *) tfin->Get("EP_correlations");

    corr_HFm1_HFp1 = (TH2D *) tdEPcorr->Get("HFp1_vs_HFm1");
    corr_trackmid1_HFm1 = (TH2D *) tdEPcorr->Get("HFm1_vs_trackmid1");
    corr_trackmid1_HFp1 = (TH2D *) tdEPcorr->Get("HFp1_vs_trackmid1");
    corr_trackm1_HFm1 = (TH2D *) tdEPcorr->Get("HFm1_vs_trackm1");
    corr_trackm1_trackp1 = (TH2D *) tdEPcorr->Get("trackp1_vs_trackm1");
    corr_trackm1_HFp1 = (TH2D *) tdEPcorr->Get("HFp1_vs_trackm1");
    corr_trackp1_HFm1 = (TH2D *) tdEPcorr->Get("HFm1_vs_trackp1");
    corr_trackp1_trackm1 = (TH2D *) tdEPcorr->Get("trackm1_vs_trackp1");
    corr_trackp1_HFp1 = (TH2D *) tdEPcorr->Get("HFp1_vs_trackp1");

    corr_HFm1_trackm2 = (TH2D *) tdEPcorr->Get("trackm2_vs_HFm1");
    corr_HFm1_trackp2 = (TH2D *) tdEPcorr->Get("trackp2_vs_HFm1");
    corr_HFp1_trackm2 = (TH2D *) tdEPcorr->Get("trackm2_vs_HFp1");
    corr_HFp1_trackp2 = (TH2D *) tdEPcorr->Get("trackp2_vs_HFp1");
    corr_HFm1_HFp2 = (TH2D *) tdEPcorr->Get("HFp2_vs_HFm1");
    corr_HFp1_HFm2 = (TH2D *) tdEPcorr->Get("HFm2_vs_HFp1");
    corr_trackmid1_HFm2 = (TH2D *) tdEPcorr->Get("HFm2_vs_trackmid1");
    corr_trackmid1_HFp2 = (TH2D *) tdEPcorr->Get("HFp2_vs_trackmid1");
    corr_trackm1_HFm2 = (TH2D *) tdEPcorr->Get("HFm2_vs_trackm1");
    corr_trackm1_trackp2 = (TH2D *) tdEPcorr->Get("trackp2_vs_trackm1");
    corr_trackm1_HFp2 = (TH2D *) tdEPcorr->Get("HFp2_vs_trackm1");
    corr_trackp1_HFm2 = (TH2D *) tdEPcorr->Get("HFm2_vs_trackp1");
    corr_trackp1_trackm2 = (TH2D *) tdEPcorr->Get("trackm2_vs_trackp1");
    corr_trackp1_HFp2 = (TH2D *) tdEPcorr->Get("HFp2_vs_trackp1");

    corr_HFm2_HFp2 = (TH2D *) tdEPcorr->Get("HFp2_vs_HFm2");
    corr_trackmid2_HFm2 = (TH2D *) tdEPcorr->Get("HFm2_vs_trackmid2");
    corr_trackmid2_HFp2 = (TH2D *) tdEPcorr->Get("HFp2_vs_trackmid2");
    corr_trackm2_HFm2 = (TH2D *) tdEPcorr->Get("HFm2_vs_trackm2");
    corr_trackm2_trackp2 = (TH2D *) tdEPcorr->Get("trackp2_vs_trackm2");
    corr_trackm2_HFp2 = (TH2D *) tdEPcorr->Get("HFp2_vs_trackm2");
    corr_trackp2_HFm2 = (TH2D *) tdEPcorr->Get("HFm2_vs_trackp2");
    corr_trackp2_HFp2 = (TH2D *) tdEPcorr->Get("HFp2_vs_trackp2");


    tdEPcos = (TDirectory *) tfin->Get("EP_cosines");

    cos_HFm1_HFp1 = (TH1D *) tdEPcos->Get("cos_HFm1_HFp1");
    cos_trackmid1_HFm1 = (TH1D *) tdEPcos->Get("cos_trackmid1_HFm1");
    cos_trackmid1_HFp1 = (TH1D *) tdEPcos->Get("cos_trackmid1_HFp1");
    cos_trackm1_HFm1 = (TH1D *) tdEPcos->Get("cos_trackm1_HFm1");
    cos_trackm1_trackp1 = (TH1D *) tdEPcos->Get("cos_trackm1_trackp1");
    cos_trackm1_HFp1 = (TH1D *) tdEPcos->Get("cos_trackm1_HFp1");
    cos_trackp1_HFm1 = (TH1D *) tdEPcos->Get("cos_trackp1_HFm1");
    cos_trackp1_trackm1 = (TH1D *) tdEPcos->Get("cos_trackp1_trackm1");
    cos_trackp1_HFp1 = (TH1D *) tdEPcos->Get("cos_trackp1_HFp1");

    cos_HFm1_trackm2 = (TH1D *) tdEPcos->Get("cos_HFm1_trackm2");
    cos_HFm1_trackp2 = (TH1D *) tdEPcos->Get("cos_HFm1_trackp2");
    cos_HFp1_trackm2 = (TH1D *) tdEPcos->Get("cos_HFp1_trackm2");
    cos_HFp1_trackp2 = (TH1D *) tdEPcos->Get("cos_HFp1_trackp2");
    cos_HFm1_HFp2 = (TH1D *) tdEPcos->Get("cos_HFm1_HFp2");
    cos_HFp1_HFm2 = (TH1D *) tdEPcos->Get("cos_HFp1_HFm2");
    cos_trackmid1_HFm2 = (TH1D *) tdEPcos->Get("cos_trackmid1_HFm2");
    cos_trackmid1_HFp2 = (TH1D *) tdEPcos->Get("cos_trackmid1_HFp2");
    cos_trackm1_HFm2 = (TH1D *) tdEPcos->Get("cos_trackm1_HFm2");
    cos_trackm1_trackp2 = (TH1D *) tdEPcos->Get("cos_trackm1_trackp2");
    cos_trackm1_HFp2 = (TH1D *) tdEPcos->Get("cos_trackm1_HFp2");
    cos_trackp1_HFm2 = (TH1D *) tdEPcos->Get("cos_trackp1_HFm2");
    cos_trackp1_trackm2 = (TH1D *) tdEPcos->Get("cos_trackp1_trackm2");
    cos_trackp1_HFp2 = (TH1D *) tdEPcos->Get("cos_trackp1_HFp2");

    cos_HFm2_HFp2 = (TH1D *) tdEPcos->Get("cos_HFm2_HFp2");
    cos_trackmid2_HFm2 = (TH1D *) tdEPcos->Get("cos_trackmid2_HFm2");
    cos_trackmid2_HFp2 = (TH1D *) tdEPcos->Get("cos_trackmid2_HFp2");
    cos_trackm2_HFm2 = (TH1D *) tdEPcos->Get("cos_trackm2_HFm2");
    cos_trackm2_trackp2 = (TH1D *) tdEPcos->Get("cos_trackm2_trackp2");
    cos_trackm2_HFp2 = (TH1D *) tdEPcos->Get("cos_trackm2_HFp2");
    cos_trackp2_HFm2 = (TH1D *) tdEPcos->Get("cos_trackp2_HFm2");
    cos_trackp2_HFp2 = (TH1D *) tdEPcos->Get("cos_trackp2_HFp2");


    corr_HFm1_HFp1->SetTitle("");
    corr_HFm1_HFp1->SetStats(0);
    corr_HFm1_HFp1->SetXTitle("#Psi_{1}{HF-}");
    corr_HFm1_HFp1->SetYTitle("#Psi_{1}{HF+}");
    corr_HFm1_HFp1->GetXaxis()->CenterTitle(kTRUE);
    corr_HFm1_HFp1->GetYaxis()->CenterTitle(kTRUE);
    corr_HFm1_HFp1->GetXaxis()->SetTitleSize(xtlsize1x1);
    corr_HFm1_HFp1->GetYaxis()->SetTitleSize(ytlsize1x1);
    corr_HFm1_HFp1->GetXaxis()->SetTitleOffset(xtloffset1x1);
    corr_HFm1_HFp1->GetYaxis()->SetTitleOffset(ytloffset1x1);
    corr_HFm1_HFp1->GetXaxis()->SetLabelSize(xlbsize1x1);
    corr_HFm1_HFp1->GetYaxis()->SetLabelSize(ylbsize1x1);
    corr_HFm1_HFp1->GetXaxis()->SetLabelOffset(xlboffset1x1);
    corr_HFm1_HFp1->GetYaxis()->SetLabelOffset(ylboffset1x1);
    corr_HFm1_HFp1->GetZaxis()->SetRangeUser(zcolmin1v1,zcolmax1v1);

    corr_trackmid1_HFm1->SetTitle("");
    corr_trackmid1_HFm1->SetStats(0);
    corr_trackmid1_HFm1->SetXTitle("#Psi_{1}{trackmid}");
    corr_trackmid1_HFm1->SetYTitle("#Psi_{1}{HF-}");
    corr_trackmid1_HFm1->GetXaxis()->CenterTitle(kTRUE);
    corr_trackmid1_HFm1->GetYaxis()->CenterTitle(kTRUE);
    corr_trackmid1_HFm1->GetXaxis()->SetTitleSize(xtlsize1x1);
    corr_trackmid1_HFm1->GetYaxis()->SetTitleSize(ytlsize1x1);
    corr_trackmid1_HFm1->GetXaxis()->SetTitleOffset(xtloffset1x1);
    corr_trackmid1_HFm1->GetYaxis()->SetTitleOffset(ytloffset1x1);
    corr_trackmid1_HFm1->GetXaxis()->SetLabelSize(xlbsize1x1);
    corr_trackmid1_HFm1->GetYaxis()->SetLabelSize(ylbsize1x1);
    corr_trackmid1_HFm1->GetXaxis()->SetLabelOffset(xlboffset1x1);
    corr_trackmid1_HFm1->GetYaxis()->SetLabelOffset(ylboffset1x1);
    corr_trackmid1_HFm1->GetZaxis()->SetRangeUser(zcolmin1v1,zcolmax1v1);

    corr_trackmid1_HFp1->SetTitle("");
    corr_trackmid1_HFp1->SetStats(0);
    corr_trackmid1_HFp1->SetXTitle("#Psi_{1}{trackmid}");
    corr_trackmid1_HFp1->SetYTitle("#Psi_{1}{HF+}");
    corr_trackmid1_HFp1->GetXaxis()->CenterTitle(kTRUE);
    corr_trackmid1_HFp1->GetYaxis()->CenterTitle(kTRUE);
    corr_trackmid1_HFp1->GetXaxis()->SetTitleSize(xtlsize1x1);
    corr_trackmid1_HFp1->GetYaxis()->SetTitleSize(ytlsize1x1);
    corr_trackmid1_HFp1->GetXaxis()->SetTitleOffset(xtloffset1x1);
    corr_trackmid1_HFp1->GetYaxis()->SetTitleOffset(ytloffset1x1);
    corr_trackmid1_HFp1->GetXaxis()->SetLabelSize(xlbsize1x1);
    corr_trackmid1_HFp1->GetYaxis()->SetLabelSize(ylbsize1x1);
    corr_trackmid1_HFp1->GetXaxis()->SetLabelOffset(xlboffset1x1);
    corr_trackmid1_HFp1->GetYaxis()->SetLabelOffset(ylboffset1x1);
    corr_trackmid1_HFp1->GetZaxis()->SetRangeUser(zcolmin1v1,zcolmax1v1);

    corr_trackm1_HFm1->SetTitle("");
    corr_trackm1_HFm1->SetStats(0);
    corr_trackm1_HFm1->SetXTitle("#Psi_{1}{track-}");
    corr_trackm1_HFm1->SetYTitle("#Psi_{1}{HF-}");
    corr_trackm1_HFm1->GetXaxis()->CenterTitle(kTRUE);
    corr_trackm1_HFm1->GetYaxis()->CenterTitle(kTRUE);
    corr_trackm1_HFm1->GetXaxis()->SetTitleSize(xtlsize1x1);
    corr_trackm1_HFm1->GetYaxis()->SetTitleSize(ytlsize1x1);
    corr_trackm1_HFm1->GetXaxis()->SetTitleOffset(xtloffset1x1);
    corr_trackm1_HFm1->GetYaxis()->SetTitleOffset(ytloffset1x1);
    corr_trackm1_HFm1->GetXaxis()->SetLabelSize(xlbsize1x1);
    corr_trackm1_HFm1->GetYaxis()->SetLabelSize(ylbsize1x1);
    corr_trackm1_HFm1->GetXaxis()->SetLabelOffset(xlboffset1x1);
    corr_trackm1_HFm1->GetYaxis()->SetLabelOffset(ylboffset1x1);
    corr_trackm1_HFm1->GetZaxis()->SetRangeUser(zcolmin1v1,zcolmax1v1);

    corr_trackm1_trackp1->SetTitle("");
    corr_trackm1_trackp1->SetStats(0);
    corr_trackm1_trackp1->SetXTitle("#Psi_{1}{track-}");
    corr_trackm1_trackp1->SetYTitle("#Psi_{1}{track+}");
    corr_trackm1_trackp1->GetXaxis()->CenterTitle(kTRUE);
    corr_trackm1_trackp1->GetYaxis()->CenterTitle(kTRUE);
    corr_trackm1_trackp1->GetXaxis()->SetTitleSize(xtlsize1x1);
    corr_trackm1_trackp1->GetYaxis()->SetTitleSize(ytlsize1x1);
    corr_trackm1_trackp1->GetXaxis()->SetTitleOffset(xtloffset1x1);
    corr_trackm1_trackp1->GetYaxis()->SetTitleOffset(ytloffset1x1);
    corr_trackm1_trackp1->GetXaxis()->SetLabelSize(xlbsize1x1);
    corr_trackm1_trackp1->GetYaxis()->SetLabelSize(ylbsize1x1);
    corr_trackm1_trackp1->GetXaxis()->SetLabelOffset(xlboffset1x1);
    corr_trackm1_trackp1->GetYaxis()->SetLabelOffset(ylboffset1x1);
    corr_trackm1_trackp1->GetZaxis()->SetRangeUser(zcolmin1v1,zcolmax1v1);

    corr_trackm1_HFp1->SetTitle("");
    corr_trackm1_HFp1->SetStats(0);
    corr_trackm1_HFp1->SetXTitle("#Psi_{1}{track-}");
    corr_trackm1_HFp1->SetYTitle("#Psi_{1}{HF+}");
    corr_trackm1_HFp1->GetXaxis()->CenterTitle(kTRUE);
    corr_trackm1_HFp1->GetYaxis()->CenterTitle(kTRUE);
    corr_trackm1_HFp1->GetXaxis()->SetTitleSize(xtlsize1x1);
    corr_trackm1_HFp1->GetYaxis()->SetTitleSize(ytlsize1x1);
    corr_trackm1_HFp1->GetXaxis()->SetTitleOffset(xtloffset1x1);
    corr_trackm1_HFp1->GetYaxis()->SetTitleOffset(ytloffset1x1);
    corr_trackm1_HFp1->GetXaxis()->SetLabelSize(xlbsize1x1);
    corr_trackm1_HFp1->GetYaxis()->SetLabelSize(ylbsize1x1);
    corr_trackm1_HFp1->GetXaxis()->SetLabelOffset(xlboffset1x1);
    corr_trackm1_HFp1->GetYaxis()->SetLabelOffset(ylboffset1x1);
    corr_trackm1_HFp1->GetZaxis()->SetRangeUser(zcolmin1v1,zcolmax1v1);

    corr_trackp1_HFm1->SetTitle("");
    corr_trackp1_HFm1->SetStats(0);
    corr_trackp1_HFm1->SetXTitle("#Psi_{1}{track+}");
    corr_trackp1_HFm1->SetYTitle("#Psi_{1}{HF-}");
    corr_trackp1_HFm1->GetXaxis()->CenterTitle(kTRUE);
    corr_trackp1_HFm1->GetYaxis()->CenterTitle(kTRUE);
    corr_trackp1_HFm1->GetXaxis()->SetTitleSize(xtlsize1x1);
    corr_trackp1_HFm1->GetYaxis()->SetTitleSize(ytlsize1x1);
    corr_trackp1_HFm1->GetXaxis()->SetTitleOffset(xtloffset1x1);
    corr_trackp1_HFm1->GetYaxis()->SetTitleOffset(ytloffset1x1);
    corr_trackp1_HFm1->GetXaxis()->SetLabelSize(xlbsize1x1);
    corr_trackp1_HFm1->GetYaxis()->SetLabelSize(ylbsize1x1);
    corr_trackp1_HFm1->GetXaxis()->SetLabelOffset(xlboffset1x1);
    corr_trackp1_HFm1->GetYaxis()->SetLabelOffset(ylboffset1x1);
    corr_trackp1_HFm1->GetZaxis()->SetRangeUser(zcolmin1v1,zcolmax1v1);

    corr_trackp1_trackm1->SetTitle("");
    corr_trackp1_trackm1->SetStats(0);
    corr_trackp1_trackm1->SetXTitle("#Psi_{1}{track+}");
    corr_trackp1_trackm1->SetYTitle("#Psi_{1}{track-}");
    corr_trackp1_trackm1->GetXaxis()->CenterTitle(kTRUE);
    corr_trackp1_trackm1->GetYaxis()->CenterTitle(kTRUE);
    corr_trackp1_trackm1->GetXaxis()->SetTitleSize(xtlsize1x1);
    corr_trackp1_trackm1->GetYaxis()->SetTitleSize(ytlsize1x1);
    corr_trackp1_trackm1->GetXaxis()->SetTitleOffset(xtloffset1x1);
    corr_trackp1_trackm1->GetYaxis()->SetTitleOffset(ytloffset1x1);
    corr_trackp1_trackm1->GetXaxis()->SetLabelSize(xlbsize1x1);
    corr_trackp1_trackm1->GetYaxis()->SetLabelSize(ylbsize1x1);
    corr_trackp1_trackm1->GetXaxis()->SetLabelOffset(xlboffset1x1);
    corr_trackp1_trackm1->GetYaxis()->SetLabelOffset(ylboffset1x1);
    corr_trackp1_trackm1->GetZaxis()->SetRangeUser(zcolmin1v1,zcolmax1v1);

    corr_trackp1_HFp1->SetTitle("");
    corr_trackp1_HFp1->SetStats(0);
    corr_trackp1_HFp1->SetXTitle("#Psi_{1}{track+}");
    corr_trackp1_HFp1->SetYTitle("#Psi_{1}{HF+}");
    corr_trackp1_HFp1->GetXaxis()->CenterTitle(kTRUE);
    corr_trackp1_HFp1->GetYaxis()->CenterTitle(kTRUE);
    corr_trackp1_HFp1->GetXaxis()->SetTitleSize(xtlsize1x1);
    corr_trackp1_HFp1->GetYaxis()->SetTitleSize(ytlsize1x1);
    corr_trackp1_HFp1->GetXaxis()->SetTitleOffset(xtloffset1x1);
    corr_trackp1_HFp1->GetYaxis()->SetTitleOffset(ytloffset1x1);
    corr_trackp1_HFp1->GetXaxis()->SetLabelSize(xlbsize1x1);
    corr_trackp1_HFp1->GetYaxis()->SetLabelSize(ylbsize1x1);
    corr_trackp1_HFp1->GetXaxis()->SetLabelOffset(xlboffset1x1);
    corr_trackp1_HFp1->GetYaxis()->SetLabelOffset(ylboffset1x1);
    corr_trackp1_HFp1->GetZaxis()->SetRangeUser(zcolmin1v1,zcolmax1v1);

    corr_HFm1_trackm2->SetTitle("");
    corr_HFm1_trackm2->SetStats(0);
    corr_HFm1_trackm2->SetXTitle("#Psi_{1}{HF-}");
    corr_HFm1_trackm2->SetYTitle("#Psi_{2}{track-}");
    corr_HFm1_trackm2->GetXaxis()->CenterTitle(kTRUE);
    corr_HFm1_trackm2->GetYaxis()->CenterTitle(kTRUE);
    corr_HFm1_trackm2->GetXaxis()->SetTitleSize(xtlsize1x1);
    corr_HFm1_trackm2->GetYaxis()->SetTitleSize(ytlsize1x1);
    corr_HFm1_trackm2->GetXaxis()->SetTitleOffset(xtloffset1x1);
    corr_HFm1_trackm2->GetYaxis()->SetTitleOffset(ytloffset1x1);
    corr_HFm1_trackm2->GetXaxis()->SetLabelSize(xlbsize1x1);
    corr_HFm1_trackm2->GetYaxis()->SetLabelSize(ylbsize1x1);
    corr_HFm1_trackm2->GetXaxis()->SetLabelOffset(xlboffset1x1);
    corr_HFm1_trackm2->GetYaxis()->SetLabelOffset(ylboffset1x1);
    corr_HFm1_trackm2->GetZaxis()->SetRangeUser(zcolmin1v2,zcolmax1v2);

    corr_HFm1_trackp2->SetTitle("");
    corr_HFm1_trackp2->SetStats(0);
    corr_HFm1_trackp2->SetXTitle("#Psi_{1}{HF-}");
    corr_HFm1_trackp2->SetYTitle("#Psi_{2}{track+}");
    corr_HFm1_trackp2->GetXaxis()->CenterTitle(kTRUE);
    corr_HFm1_trackp2->GetYaxis()->CenterTitle(kTRUE);
    corr_HFm1_trackp2->GetXaxis()->SetTitleSize(xtlsize1x1);
    corr_HFm1_trackp2->GetYaxis()->SetTitleSize(ytlsize1x1);
    corr_HFm1_trackp2->GetXaxis()->SetTitleOffset(xtloffset1x1);
    corr_HFm1_trackp2->GetYaxis()->SetTitleOffset(ytloffset1x1);
    corr_HFm1_trackp2->GetXaxis()->SetLabelSize(xlbsize1x1);
    corr_HFm1_trackp2->GetYaxis()->SetLabelSize(ylbsize1x1);
    corr_HFm1_trackp2->GetXaxis()->SetLabelOffset(xlboffset1x1);
    corr_HFm1_trackp2->GetYaxis()->SetLabelOffset(ylboffset1x1);
    corr_HFm1_trackp2->GetZaxis()->SetRangeUser(zcolmin1v2,zcolmax1v2);

    corr_HFp1_trackm2->SetTitle("");
    corr_HFp1_trackm2->SetStats(0);
    corr_HFp1_trackm2->SetXTitle("#Psi_{1}{HF+}");
    corr_HFp1_trackm2->SetYTitle("#Psi_{2}{track-}");
    corr_HFp1_trackm2->GetXaxis()->CenterTitle(kTRUE);
    corr_HFp1_trackm2->GetYaxis()->CenterTitle(kTRUE);
    corr_HFp1_trackm2->GetXaxis()->SetTitleSize(xtlsize1x1);
    corr_HFp1_trackm2->GetYaxis()->SetTitleSize(ytlsize1x1);
    corr_HFp1_trackm2->GetXaxis()->SetTitleOffset(xtloffset1x1);
    corr_HFp1_trackm2->GetYaxis()->SetTitleOffset(ytloffset1x1);
    corr_HFp1_trackm2->GetXaxis()->SetLabelSize(xlbsize1x1);
    corr_HFp1_trackm2->GetYaxis()->SetLabelSize(ylbsize1x1);
    corr_HFp1_trackm2->GetXaxis()->SetLabelOffset(xlboffset1x1);
    corr_HFp1_trackm2->GetYaxis()->SetLabelOffset(ylboffset1x1);
    corr_HFp1_trackm2->GetZaxis()->SetRangeUser(zcolmin1v2,zcolmax1v2);

    corr_HFp1_trackp2->SetTitle("");
    corr_HFp1_trackp2->SetStats(0);
    corr_HFp1_trackp2->SetXTitle("#Psi_{1}{HF+}");
    corr_HFp1_trackp2->SetYTitle("#Psi_{2}{track+}");
    corr_HFp1_trackp2->GetXaxis()->CenterTitle(kTRUE);
    corr_HFp1_trackp2->GetYaxis()->CenterTitle(kTRUE);
    corr_HFp1_trackp2->GetXaxis()->SetTitleSize(xtlsize1x1);
    corr_HFp1_trackp2->GetYaxis()->SetTitleSize(ytlsize1x1);
    corr_HFp1_trackp2->GetXaxis()->SetTitleOffset(xtloffset1x1);
    corr_HFp1_trackp2->GetYaxis()->SetTitleOffset(ytloffset1x1);
    corr_HFp1_trackp2->GetXaxis()->SetLabelSize(xlbsize1x1);
    corr_HFp1_trackp2->GetYaxis()->SetLabelSize(ylbsize1x1);
    corr_HFp1_trackp2->GetXaxis()->SetLabelOffset(xlboffset1x1);
    corr_HFp1_trackp2->GetYaxis()->SetLabelOffset(ylboffset1x1);
    corr_HFp1_trackp2->GetZaxis()->SetRangeUser(zcolmin1v2,zcolmax1v2);

    corr_HFm1_HFp2->SetTitle("");
    corr_HFm1_HFp2->SetStats(0);
    corr_HFm1_HFp2->SetXTitle("#Psi_{1}{HF-}");
    corr_HFm1_HFp2->SetYTitle("#Psi_{2}{HF+}");
    corr_HFm1_HFp2->GetXaxis()->CenterTitle(kTRUE);
    corr_HFm1_HFp2->GetYaxis()->CenterTitle(kTRUE);
    corr_HFm1_HFp2->GetXaxis()->SetTitleSize(xtlsize1x1);
    corr_HFm1_HFp2->GetYaxis()->SetTitleSize(ytlsize1x1);
    corr_HFm1_HFp2->GetXaxis()->SetTitleOffset(xtloffset1x1);
    corr_HFm1_HFp2->GetYaxis()->SetTitleOffset(ytloffset1x1);
    corr_HFm1_HFp2->GetXaxis()->SetLabelSize(xlbsize1x1);
    corr_HFm1_HFp2->GetYaxis()->SetLabelSize(ylbsize1x1);
    corr_HFm1_HFp2->GetXaxis()->SetLabelOffset(xlboffset1x1);
    corr_HFm1_HFp2->GetYaxis()->SetLabelOffset(ylboffset1x1);
    corr_HFm1_HFp2->GetZaxis()->SetRangeUser(zcolmin1v2,zcolmax1v2);

    corr_HFp1_HFm2->SetTitle("");
    corr_HFp1_HFm2->SetStats(0);
    corr_HFp1_HFm2->SetXTitle("#Psi_{1}{HF+}");
    corr_HFp1_HFm2->SetYTitle("#Psi_{2}{HF-}");
    corr_HFp1_HFm2->GetXaxis()->CenterTitle(kTRUE);
    corr_HFp1_HFm2->GetYaxis()->CenterTitle(kTRUE);
    corr_HFp1_HFm2->GetXaxis()->SetTitleSize(xtlsize1x1);
    corr_HFp1_HFm2->GetYaxis()->SetTitleSize(ytlsize1x1);
    corr_HFp1_HFm2->GetXaxis()->SetTitleOffset(xtloffset1x1);
    corr_HFp1_HFm2->GetYaxis()->SetTitleOffset(ytloffset1x1);
    corr_HFp1_HFm2->GetXaxis()->SetLabelSize(xlbsize1x1);
    corr_HFp1_HFm2->GetYaxis()->SetLabelSize(ylbsize1x1);
    corr_HFp1_HFm2->GetXaxis()->SetLabelOffset(xlboffset1x1);
    corr_HFp1_HFm2->GetYaxis()->SetLabelOffset(ylboffset1x1);
    corr_HFp1_HFm2->GetZaxis()->SetRangeUser(zcolmin1v2,zcolmax1v2);

    corr_trackmid1_HFm2->SetTitle("");
    corr_trackmid1_HFm2->SetStats(0);
    corr_trackmid1_HFm2->SetXTitle("#Psi_{1}{trackmid}");
    corr_trackmid1_HFm2->SetYTitle("#Psi_{2}{HF-}");
    corr_trackmid1_HFm2->GetXaxis()->CenterTitle(kTRUE);
    corr_trackmid1_HFm2->GetYaxis()->CenterTitle(kTRUE);
    corr_trackmid1_HFm2->GetXaxis()->SetTitleSize(xtlsize1x1);
    corr_trackmid1_HFm2->GetYaxis()->SetTitleSize(ytlsize1x1);
    corr_trackmid1_HFm2->GetXaxis()->SetTitleOffset(xtloffset1x1);
    corr_trackmid1_HFm2->GetYaxis()->SetTitleOffset(ytloffset1x1);
    corr_trackmid1_HFm2->GetXaxis()->SetLabelSize(xlbsize1x1);
    corr_trackmid1_HFm2->GetYaxis()->SetLabelSize(ylbsize1x1);
    corr_trackmid1_HFm2->GetXaxis()->SetLabelOffset(xlboffset1x1);
    corr_trackmid1_HFm2->GetYaxis()->SetLabelOffset(ylboffset1x1);
    corr_trackmid1_HFm2->GetZaxis()->SetRangeUser(zcolmin1v2,zcolmax1v2);

    corr_trackmid1_HFp2->SetTitle("");
    corr_trackmid1_HFp2->SetStats(0);
    corr_trackmid1_HFp2->SetXTitle("#Psi_{1}{trackmid}");
    corr_trackmid1_HFp2->SetYTitle("#Psi_{2}{HF+}");
    corr_trackmid1_HFp2->GetXaxis()->CenterTitle(kTRUE);
    corr_trackmid1_HFp2->GetYaxis()->CenterTitle(kTRUE);
    corr_trackmid1_HFp2->GetXaxis()->SetTitleSize(xtlsize1x1);
    corr_trackmid1_HFp2->GetYaxis()->SetTitleSize(ytlsize1x1);
    corr_trackmid1_HFp2->GetXaxis()->SetTitleOffset(xtloffset1x1);
    corr_trackmid1_HFp2->GetYaxis()->SetTitleOffset(ytloffset1x1);
    corr_trackmid1_HFp2->GetXaxis()->SetLabelSize(xlbsize1x1);
    corr_trackmid1_HFp2->GetYaxis()->SetLabelSize(ylbsize1x1);
    corr_trackmid1_HFp2->GetXaxis()->SetLabelOffset(xlboffset1x1);
    corr_trackmid1_HFp2->GetYaxis()->SetLabelOffset(ylboffset1x1);
    corr_trackmid1_HFp2->GetZaxis()->SetRangeUser(zcolmin1v2,zcolmax1v2);

    corr_trackm1_HFm2->SetTitle("");
    corr_trackm1_HFm2->SetStats(0);
    corr_trackm1_HFm2->SetXTitle("#Psi_{1}{track-}");
    corr_trackm1_HFm2->SetYTitle("#Psi_{2}{HF-}");
    corr_trackm1_HFm2->GetXaxis()->CenterTitle(kTRUE);
    corr_trackm1_HFm2->GetYaxis()->CenterTitle(kTRUE);
    corr_trackm1_HFm2->GetXaxis()->SetTitleSize(xtlsize1x1);
    corr_trackm1_HFm2->GetYaxis()->SetTitleSize(ytlsize1x1);
    corr_trackm1_HFm2->GetXaxis()->SetTitleOffset(xtloffset1x1);
    corr_trackm1_HFm2->GetYaxis()->SetTitleOffset(ytloffset1x1);
    corr_trackm1_HFm2->GetXaxis()->SetLabelSize(xlbsize1x1);
    corr_trackm1_HFm2->GetYaxis()->SetLabelSize(ylbsize1x1);
    corr_trackm1_HFm2->GetXaxis()->SetLabelOffset(xlboffset1x1);
    corr_trackm1_HFm2->GetYaxis()->SetLabelOffset(ylboffset1x1);
    corr_trackm1_HFm2->GetZaxis()->SetRangeUser(zcolmin1v2,zcolmax1v2);

    corr_trackm1_trackp2->SetTitle("");
    corr_trackm1_trackp2->SetStats(0);
    corr_trackm1_trackp2->SetXTitle("#Psi_{1}{track-}");
    corr_trackm1_trackp2->SetYTitle("#Psi_{2}{track+}");
    corr_trackm1_trackp2->GetXaxis()->CenterTitle(kTRUE);
    corr_trackm1_trackp2->GetYaxis()->CenterTitle(kTRUE);
    corr_trackm1_trackp2->GetXaxis()->SetTitleSize(xtlsize1x1);
    corr_trackm1_trackp2->GetYaxis()->SetTitleSize(ytlsize1x1);
    corr_trackm1_trackp2->GetXaxis()->SetTitleOffset(xtloffset1x1);
    corr_trackm1_trackp2->GetYaxis()->SetTitleOffset(ytloffset1x1);
    corr_trackm1_trackp2->GetXaxis()->SetLabelSize(xlbsize1x1);
    corr_trackm1_trackp2->GetYaxis()->SetLabelSize(ylbsize1x1);
    corr_trackm1_trackp2->GetXaxis()->SetLabelOffset(xlboffset1x1);
    corr_trackm1_trackp2->GetYaxis()->SetLabelOffset(ylboffset1x1);
    corr_trackm1_trackp2->GetZaxis()->SetRangeUser(zcolmin1v2,zcolmax1v2);

    corr_trackm1_HFp2->SetTitle("");
    corr_trackm1_HFp2->SetStats(0);
    corr_trackm1_HFp2->SetXTitle("#Psi_{1}{track-}");
    corr_trackm1_HFp2->SetYTitle("#Psi_{2}{HF+}");
    corr_trackm1_HFp2->GetXaxis()->CenterTitle(kTRUE);
    corr_trackm1_HFp2->GetYaxis()->CenterTitle(kTRUE);
    corr_trackm1_HFp2->GetXaxis()->SetTitleSize(xtlsize1x1);
    corr_trackm1_HFp2->GetYaxis()->SetTitleSize(ytlsize1x1);
    corr_trackm1_HFp2->GetXaxis()->SetTitleOffset(xtloffset1x1);
    corr_trackm1_HFp2->GetYaxis()->SetTitleOffset(ytloffset1x1);
    corr_trackm1_HFp2->GetXaxis()->SetLabelSize(xlbsize1x1);
    corr_trackm1_HFp2->GetYaxis()->SetLabelSize(ylbsize1x1);
    corr_trackm1_HFp2->GetXaxis()->SetLabelOffset(xlboffset1x1);
    corr_trackm1_HFp2->GetYaxis()->SetLabelOffset(ylboffset1x1);
    corr_trackm1_HFp2->GetZaxis()->SetRangeUser(zcolmin1v2,zcolmax1v2);

    corr_trackp1_HFm2->SetTitle("");
    corr_trackp1_HFm2->SetStats(0);
    corr_trackp1_HFm2->SetXTitle("#Psi_{1}{track+}");
    corr_trackp1_HFm2->SetYTitle("#Psi_{2}{HF-}");
    corr_trackp1_HFm2->GetXaxis()->CenterTitle(kTRUE);
    corr_trackp1_HFm2->GetYaxis()->CenterTitle(kTRUE);
    corr_trackp1_HFm2->GetXaxis()->SetTitleSize(xtlsize1x1);
    corr_trackp1_HFm2->GetYaxis()->SetTitleSize(ytlsize1x1);
    corr_trackp1_HFm2->GetXaxis()->SetTitleOffset(xtloffset1x1);
    corr_trackp1_HFm2->GetYaxis()->SetTitleOffset(ytloffset1x1);
    corr_trackp1_HFm2->GetXaxis()->SetLabelSize(xlbsize1x1);
    corr_trackp1_HFm2->GetYaxis()->SetLabelSize(ylbsize1x1);
    corr_trackp1_HFm2->GetXaxis()->SetLabelOffset(xlboffset1x1);
    corr_trackp1_HFm2->GetYaxis()->SetLabelOffset(ylboffset1x1);
    corr_trackp1_HFm2->GetZaxis()->SetRangeUser(zcolmin1v2,zcolmax1v2);

    corr_trackp1_trackm2->SetTitle("");
    corr_trackp1_trackm2->SetStats(0);
    corr_trackp1_trackm2->SetXTitle("#Psi_{1}{track+}");
    corr_trackp1_trackm2->SetYTitle("#Psi_{2}{track-}");
    corr_trackp1_trackm2->GetXaxis()->CenterTitle(kTRUE);
    corr_trackp1_trackm2->GetYaxis()->CenterTitle(kTRUE);
    corr_trackp1_trackm2->GetXaxis()->SetTitleSize(xtlsize1x1);
    corr_trackp1_trackm2->GetYaxis()->SetTitleSize(ytlsize1x1);
    corr_trackp1_trackm2->GetXaxis()->SetTitleOffset(xtloffset1x1);
    corr_trackp1_trackm2->GetYaxis()->SetTitleOffset(ytloffset1x1);
    corr_trackp1_trackm2->GetXaxis()->SetLabelSize(xlbsize1x1);
    corr_trackp1_trackm2->GetYaxis()->SetLabelSize(ylbsize1x1);
    corr_trackp1_trackm2->GetXaxis()->SetLabelOffset(xlboffset1x1);
    corr_trackp1_trackm2->GetYaxis()->SetLabelOffset(ylboffset1x1);
    corr_trackp1_trackm2->GetZaxis()->SetRangeUser(zcolmin1v2,zcolmax1v2);

    corr_trackp1_HFp2->SetTitle("");
    corr_trackp1_HFp2->SetStats(0);
    corr_trackp1_HFp2->SetXTitle("#Psi_{1}{track+}");
    corr_trackp1_HFp2->SetYTitle("#Psi_{2}{HF+}");
    corr_trackp1_HFp2->GetXaxis()->CenterTitle(kTRUE);
    corr_trackp1_HFp2->GetYaxis()->CenterTitle(kTRUE);
    corr_trackp1_HFp2->GetXaxis()->SetTitleSize(xtlsize1x1);
    corr_trackp1_HFp2->GetYaxis()->SetTitleSize(ytlsize1x1);
    corr_trackp1_HFp2->GetXaxis()->SetTitleOffset(xtloffset1x1);
    corr_trackp1_HFp2->GetYaxis()->SetTitleOffset(ytloffset1x1);
    corr_trackp1_HFp2->GetXaxis()->SetLabelSize(xlbsize1x1);
    corr_trackp1_HFp2->GetYaxis()->SetLabelSize(ylbsize1x1);
    corr_trackp1_HFp2->GetXaxis()->SetLabelOffset(xlboffset1x1);
    corr_trackp1_HFp2->GetYaxis()->SetLabelOffset(ylboffset1x1);
    corr_trackp1_HFp2->GetZaxis()->SetRangeUser(zcolmin1v2,zcolmax1v2);

    corr_HFm2_HFp2->SetTitle("");
    corr_HFm2_HFp2->SetStats(0);
    corr_HFm2_HFp2->SetXTitle("#Psi_{2}{HF-}");
    corr_HFm2_HFp2->SetYTitle("#Psi_{2}{HF+}");
    corr_HFm2_HFp2->GetXaxis()->CenterTitle(kTRUE);
    corr_HFm2_HFp2->GetYaxis()->CenterTitle(kTRUE);
    corr_HFm2_HFp2->GetXaxis()->SetTitleSize(xtlsize1x1);
    corr_HFm2_HFp2->GetYaxis()->SetTitleSize(ytlsize1x1);
    corr_HFm2_HFp2->GetXaxis()->SetTitleOffset(xtloffset1x1);
    corr_HFm2_HFp2->GetYaxis()->SetTitleOffset(ytloffset1x1);
    corr_HFm2_HFp2->GetXaxis()->SetLabelSize(xlbsize1x1);
    corr_HFm2_HFp2->GetYaxis()->SetLabelSize(ylbsize1x1);
    corr_HFm2_HFp2->GetXaxis()->SetLabelOffset(xlboffset1x1);
    corr_HFm2_HFp2->GetYaxis()->SetLabelOffset(ylboffset1x1);
    corr_HFm2_HFp2->GetZaxis()->SetRangeUser(zcolmin2v2,zcolmax2v2);

    corr_trackmid2_HFm2->SetTitle("");
    corr_trackmid2_HFm2->SetStats(0);
    corr_trackmid2_HFm2->SetXTitle("#Psi_{2}{trackmid}");
    corr_trackmid2_HFm2->SetYTitle("#Psi_{2}{HF-}");
    corr_trackmid2_HFm2->GetXaxis()->CenterTitle(kTRUE);
    corr_trackmid2_HFm2->GetYaxis()->CenterTitle(kTRUE);
    corr_trackmid2_HFm2->GetXaxis()->SetTitleSize(xtlsize1x1);
    corr_trackmid2_HFm2->GetYaxis()->SetTitleSize(ytlsize1x1);
    corr_trackmid2_HFm2->GetXaxis()->SetTitleOffset(xtloffset1x1);
    corr_trackmid2_HFm2->GetYaxis()->SetTitleOffset(ytloffset1x1);
    corr_trackmid2_HFm2->GetXaxis()->SetLabelSize(xlbsize1x1);
    corr_trackmid2_HFm2->GetYaxis()->SetLabelSize(ylbsize1x1);
    corr_trackmid2_HFm2->GetXaxis()->SetLabelOffset(xlboffset1x1);
    corr_trackmid2_HFm2->GetYaxis()->SetLabelOffset(ylboffset1x1);
    corr_trackmid2_HFm2->GetZaxis()->SetRangeUser(zcolmin2v2,zcolmax2v2);

    corr_trackmid2_HFp2->SetTitle("");
    corr_trackmid2_HFp2->SetStats(0);
    corr_trackmid2_HFp2->SetXTitle("#Psi_{2}{trackmid}");
    corr_trackmid2_HFp2->SetYTitle("#Psi_{2}{HF+}");
    corr_trackmid2_HFp2->GetXaxis()->CenterTitle(kTRUE);
    corr_trackmid2_HFp2->GetYaxis()->CenterTitle(kTRUE);
    corr_trackmid2_HFp2->GetXaxis()->SetTitleSize(xtlsize1x1);
    corr_trackmid2_HFp2->GetYaxis()->SetTitleSize(ytlsize1x1);
    corr_trackmid2_HFp2->GetXaxis()->SetTitleOffset(xtloffset1x1);
    corr_trackmid2_HFp2->GetYaxis()->SetTitleOffset(ytloffset1x1);
    corr_trackmid2_HFp2->GetXaxis()->SetLabelSize(xlbsize1x1);
    corr_trackmid2_HFp2->GetYaxis()->SetLabelSize(ylbsize1x1);
    corr_trackmid2_HFp2->GetXaxis()->SetLabelOffset(xlboffset1x1);
    corr_trackmid2_HFp2->GetYaxis()->SetLabelOffset(ylboffset1x1);
    corr_trackmid2_HFp2->GetZaxis()->SetRangeUser(zcolmin2v2,zcolmax2v2);

    corr_trackm2_HFm2->SetTitle("");
    corr_trackm2_HFm2->SetStats(0);
    corr_trackm2_HFm2->SetXTitle("#Psi_{2}{track-}");
    corr_trackm2_HFm2->SetYTitle("#Psi_{2}{HF-}");
    corr_trackm2_HFm2->GetXaxis()->CenterTitle(kTRUE);
    corr_trackm2_HFm2->GetYaxis()->CenterTitle(kTRUE);
    corr_trackm2_HFm2->GetXaxis()->SetTitleSize(xtlsize1x1);
    corr_trackm2_HFm2->GetYaxis()->SetTitleSize(ytlsize1x1);
    corr_trackm2_HFm2->GetXaxis()->SetTitleOffset(xtloffset1x1);
    corr_trackm2_HFm2->GetYaxis()->SetTitleOffset(ytloffset1x1);
    corr_trackm2_HFm2->GetXaxis()->SetLabelSize(xlbsize1x1);
    corr_trackm2_HFm2->GetYaxis()->SetLabelSize(ylbsize1x1);
    corr_trackm2_HFm2->GetXaxis()->SetLabelOffset(xlboffset1x1);
    corr_trackm2_HFm2->GetYaxis()->SetLabelOffset(ylboffset1x1);
    corr_trackm2_HFm2->GetZaxis()->SetRangeUser(zcolmin2v2,zcolmax2v2);

    corr_trackm2_trackp2->SetTitle("");
    corr_trackm2_trackp2->SetStats(0);
    corr_trackm2_trackp2->SetXTitle("#Psi_{2}{track-}");
    corr_trackm2_trackp2->SetYTitle("#Psi_{2}{track+}");
    corr_trackm2_trackp2->GetXaxis()->CenterTitle(kTRUE);
    corr_trackm2_trackp2->GetYaxis()->CenterTitle(kTRUE);
    corr_trackm2_trackp2->GetXaxis()->SetTitleSize(xtlsize1x1);
    corr_trackm2_trackp2->GetYaxis()->SetTitleSize(ytlsize1x1);
    corr_trackm2_trackp2->GetXaxis()->SetTitleOffset(xtloffset1x1);
    corr_trackm2_trackp2->GetYaxis()->SetTitleOffset(ytloffset1x1);
    corr_trackm2_trackp2->GetXaxis()->SetLabelSize(xlbsize1x1);
    corr_trackm2_trackp2->GetYaxis()->SetLabelSize(ylbsize1x1);
    corr_trackm2_trackp2->GetXaxis()->SetLabelOffset(xlboffset1x1);
    corr_trackm2_trackp2->GetYaxis()->SetLabelOffset(ylboffset1x1);
    corr_trackm2_trackp2->GetZaxis()->SetRangeUser(zcolmin2v2,zcolmax2v2);

    corr_trackm2_HFp2->SetTitle("");
    corr_trackm2_HFp2->SetStats(0);
    corr_trackm2_HFp2->SetXTitle("#Psi_{2}{track-}");
    corr_trackm2_HFp2->SetYTitle("#Psi_{2}{HF+}");
    corr_trackm2_HFp2->GetXaxis()->CenterTitle(kTRUE);
    corr_trackm2_HFp2->GetYaxis()->CenterTitle(kTRUE);
    corr_trackm2_HFp2->GetXaxis()->SetTitleSize(xtlsize1x1);
    corr_trackm2_HFp2->GetYaxis()->SetTitleSize(ytlsize1x1);
    corr_trackm2_HFp2->GetXaxis()->SetTitleOffset(xtloffset1x1);
    corr_trackm2_HFp2->GetYaxis()->SetTitleOffset(ytloffset1x1);
    corr_trackm2_HFp2->GetXaxis()->SetLabelSize(xlbsize1x1);
    corr_trackm2_HFp2->GetYaxis()->SetLabelSize(ylbsize1x1);
    corr_trackm2_HFp2->GetXaxis()->SetLabelOffset(xlboffset1x1);
    corr_trackm2_HFp2->GetYaxis()->SetLabelOffset(ylboffset1x1);
    corr_trackm2_HFp2->GetZaxis()->SetRangeUser(zcolmin2v2,zcolmax2v2);

    corr_trackp2_HFm2->SetTitle("");
    corr_trackp2_HFm2->SetStats(0);
    corr_trackp2_HFm2->SetXTitle("#Psi_{2}{track+}");
    corr_trackp2_HFm2->SetYTitle("#Psi_{2}{HF-}");
    corr_trackp2_HFm2->GetXaxis()->CenterTitle(kTRUE);
    corr_trackp2_HFm2->GetYaxis()->CenterTitle(kTRUE);
    corr_trackp2_HFm2->GetXaxis()->SetTitleSize(xtlsize1x1);
    corr_trackp2_HFm2->GetYaxis()->SetTitleSize(ytlsize1x1);
    corr_trackp2_HFm2->GetXaxis()->SetTitleOffset(xtloffset1x1);
    corr_trackp2_HFm2->GetYaxis()->SetTitleOffset(ytloffset1x1);
    corr_trackp2_HFm2->GetXaxis()->SetLabelSize(xlbsize1x1);
    corr_trackp2_HFm2->GetYaxis()->SetLabelSize(ylbsize1x1);
    corr_trackp2_HFm2->GetXaxis()->SetLabelOffset(xlboffset1x1);
    corr_trackp2_HFm2->GetYaxis()->SetLabelOffset(ylboffset1x1);
    corr_trackp2_HFm2->GetZaxis()->SetRangeUser(zcolmin2v2,zcolmax2v2);

    corr_trackp2_HFp2->SetTitle("");
    corr_trackp2_HFp2->SetStats(0);
    corr_trackp2_HFp2->SetXTitle("#Psi_{2}{track+}");
    corr_trackp2_HFp2->SetYTitle("#Psi_{2}{HF+}");
    corr_trackp2_HFp2->GetXaxis()->CenterTitle(kTRUE);
    corr_trackp2_HFp2->GetYaxis()->CenterTitle(kTRUE);
    corr_trackp2_HFp2->GetXaxis()->SetTitleSize(xtlsize1x1);
    corr_trackp2_HFp2->GetYaxis()->SetTitleSize(ytlsize1x1);
    corr_trackp2_HFp2->GetXaxis()->SetTitleOffset(xtloffset1x1);
    corr_trackp2_HFp2->GetYaxis()->SetTitleOffset(ytloffset1x1);
    corr_trackp2_HFp2->GetXaxis()->SetLabelSize(xlbsize1x1);
    corr_trackp2_HFp2->GetYaxis()->SetLabelSize(ylbsize1x1);
    corr_trackp2_HFp2->GetXaxis()->SetLabelOffset(xlboffset1x1);
    corr_trackp2_HFp2->GetYaxis()->SetLabelOffset(ylboffset1x1);
    corr_trackp2_HFp2->GetZaxis()->SetRangeUser(zcolmin2v2,zcolmax2v2);



    cos_HFm1_HFp1->SetTitle("");
    cos_HFm1_HFp1->SetStats(0);
    cos_HFm1_HFp1->SetXTitle("<cos(#Psi_{1}{HF-} - #Psi_{1}{HF+})>");
    cos_HFm1_HFp1->SetYTitle("");
    cos_HFm1_HFp1->GetXaxis()->CenterTitle(kTRUE);
    cos_HFm1_HFp1->GetYaxis()->CenterTitle(kTRUE);
    cos_HFm1_HFp1->GetXaxis()->SetTitleSize(xtlsize1x1);
    cos_HFm1_HFp1->GetYaxis()->SetTitleSize(ytlsize1x1);
    cos_HFm1_HFp1->GetXaxis()->SetTitleOffset(xtloffset1x1);
    cos_HFm1_HFp1->GetYaxis()->SetTitleOffset(ytloffset1x1);
    cos_HFm1_HFp1->GetXaxis()->SetLabelSize(xlbsize1x1);
    cos_HFm1_HFp1->GetYaxis()->SetLabelSize(ylbsize1x1);
    cos_HFm1_HFp1->GetXaxis()->SetLabelOffset(xlboffset1x1);
    cos_HFm1_HFp1->GetYaxis()->SetLabelOffset(ylboffset1x1);

    cos_trackmid1_HFm1->SetTitle("");
    cos_trackmid1_HFm1->SetStats(0);
    cos_trackmid1_HFm1->SetXTitle("<cos(#Psi_{1}{trackmid} - #Psi_{1}{HF-})>");
    cos_trackmid1_HFm1->SetYTitle("");
    cos_trackmid1_HFm1->GetXaxis()->CenterTitle(kTRUE);
    cos_trackmid1_HFm1->GetYaxis()->CenterTitle(kTRUE);
    cos_trackmid1_HFm1->GetXaxis()->SetTitleSize(xtlsize1x1);
    cos_trackmid1_HFm1->GetYaxis()->SetTitleSize(ytlsize1x1);
    cos_trackmid1_HFm1->GetXaxis()->SetTitleOffset(xtloffset1x1);
    cos_trackmid1_HFm1->GetYaxis()->SetTitleOffset(ytloffset1x1);
    cos_trackmid1_HFm1->GetXaxis()->SetLabelSize(xlbsize1x1);
    cos_trackmid1_HFm1->GetYaxis()->SetLabelSize(ylbsize1x1);
    cos_trackmid1_HFm1->GetXaxis()->SetLabelOffset(xlboffset1x1);
    cos_trackmid1_HFm1->GetYaxis()->SetLabelOffset(ylboffset1x1);

    cos_trackmid1_HFp1->SetTitle("");
    cos_trackmid1_HFp1->SetStats(0);
    cos_trackmid1_HFp1->SetXTitle("<cos(#Psi_{1}{trackmid} - #Psi_{1}{HF+})>");
    cos_trackmid1_HFp1->SetYTitle("");
    cos_trackmid1_HFp1->GetXaxis()->CenterTitle(kTRUE);
    cos_trackmid1_HFp1->GetYaxis()->CenterTitle(kTRUE);
    cos_trackmid1_HFp1->GetXaxis()->SetTitleSize(xtlsize1x1);
    cos_trackmid1_HFp1->GetYaxis()->SetTitleSize(ytlsize1x1);
    cos_trackmid1_HFp1->GetXaxis()->SetTitleOffset(xtloffset1x1);
    cos_trackmid1_HFp1->GetYaxis()->SetTitleOffset(ytloffset1x1);
    cos_trackmid1_HFp1->GetXaxis()->SetLabelSize(xlbsize1x1);
    cos_trackmid1_HFp1->GetYaxis()->SetLabelSize(ylbsize1x1);
    cos_trackmid1_HFp1->GetXaxis()->SetLabelOffset(xlboffset1x1);
    cos_trackmid1_HFp1->GetYaxis()->SetLabelOffset(ylboffset1x1);

    cos_trackm1_HFm1->SetTitle("");
    cos_trackm1_HFm1->SetStats(0);
    cos_trackm1_HFm1->SetXTitle("<cos(#Psi_{1}{track-} - #Psi_{1}{HF-})>");
    cos_trackm1_HFm1->SetYTitle("");
    cos_trackm1_HFm1->GetXaxis()->CenterTitle(kTRUE);
    cos_trackm1_HFm1->GetYaxis()->CenterTitle(kTRUE);
    cos_trackm1_HFm1->GetXaxis()->SetTitleSize(xtlsize1x1);
    cos_trackm1_HFm1->GetYaxis()->SetTitleSize(ytlsize1x1);
    cos_trackm1_HFm1->GetXaxis()->SetTitleOffset(xtloffset1x1);
    cos_trackm1_HFm1->GetYaxis()->SetTitleOffset(ytloffset1x1);
    cos_trackm1_HFm1->GetXaxis()->SetLabelSize(xlbsize1x1);
    cos_trackm1_HFm1->GetYaxis()->SetLabelSize(ylbsize1x1);
    cos_trackm1_HFm1->GetXaxis()->SetLabelOffset(xlboffset1x1);
    cos_trackm1_HFm1->GetYaxis()->SetLabelOffset(ylboffset1x1);

    cos_trackm1_trackp1->SetTitle("");
    cos_trackm1_trackp1->SetStats(0);
    cos_trackm1_trackp1->SetXTitle("<cos(#Psi_{1}{track-} - #Psi_{1}{track+})>");
    cos_trackm1_trackp1->SetYTitle("");
    cos_trackm1_trackp1->GetXaxis()->CenterTitle(kTRUE);
    cos_trackm1_trackp1->GetYaxis()->CenterTitle(kTRUE);
    cos_trackm1_trackp1->GetXaxis()->SetTitleSize(xtlsize1x1);
    cos_trackm1_trackp1->GetYaxis()->SetTitleSize(ytlsize1x1);
    cos_trackm1_trackp1->GetXaxis()->SetTitleOffset(xtloffset1x1);
    cos_trackm1_trackp1->GetYaxis()->SetTitleOffset(ytloffset1x1);
    cos_trackm1_trackp1->GetXaxis()->SetLabelSize(xlbsize1x1);
    cos_trackm1_trackp1->GetYaxis()->SetLabelSize(ylbsize1x1);
    cos_trackm1_trackp1->GetXaxis()->SetLabelOffset(xlboffset1x1);
    cos_trackm1_trackp1->GetYaxis()->SetLabelOffset(ylboffset1x1);

    cos_trackm1_HFp1->SetTitle("");
    cos_trackm1_HFp1->SetStats(0);
    cos_trackm1_HFp1->SetXTitle("<cos(#Psi_{1}{track-} - #Psi_{1}{HF+})>");
    cos_trackm1_HFp1->SetYTitle("");
    cos_trackm1_HFp1->GetXaxis()->CenterTitle(kTRUE);
    cos_trackm1_HFp1->GetYaxis()->CenterTitle(kTRUE);
    cos_trackm1_HFp1->GetXaxis()->SetTitleSize(xtlsize1x1);
    cos_trackm1_HFp1->GetYaxis()->SetTitleSize(ytlsize1x1);
    cos_trackm1_HFp1->GetXaxis()->SetTitleOffset(xtloffset1x1);
    cos_trackm1_HFp1->GetYaxis()->SetTitleOffset(ytloffset1x1);
    cos_trackm1_HFp1->GetXaxis()->SetLabelSize(xlbsize1x1);
    cos_trackm1_HFp1->GetYaxis()->SetLabelSize(ylbsize1x1);
    cos_trackm1_HFp1->GetXaxis()->SetLabelOffset(xlboffset1x1);
    cos_trackm1_HFp1->GetYaxis()->SetLabelOffset(ylboffset1x1);

    cos_trackp1_HFm1->SetTitle("");
    cos_trackp1_HFm1->SetStats(0);
    cos_trackp1_HFm1->SetXTitle("<cos(#Psi_{1}{track+} - #Psi_{1}{HF-})>");
    cos_trackp1_HFm1->SetYTitle("");
    cos_trackp1_HFm1->GetXaxis()->CenterTitle(kTRUE);
    cos_trackp1_HFm1->GetYaxis()->CenterTitle(kTRUE);
    cos_trackp1_HFm1->GetXaxis()->SetTitleSize(xtlsize1x1);
    cos_trackp1_HFm1->GetYaxis()->SetTitleSize(ytlsize1x1);
    cos_trackp1_HFm1->GetXaxis()->SetTitleOffset(xtloffset1x1);
    cos_trackp1_HFm1->GetYaxis()->SetTitleOffset(ytloffset1x1);
    cos_trackp1_HFm1->GetXaxis()->SetLabelSize(xlbsize1x1);
    cos_trackp1_HFm1->GetYaxis()->SetLabelSize(ylbsize1x1);
    cos_trackp1_HFm1->GetXaxis()->SetLabelOffset(xlboffset1x1);
    cos_trackp1_HFm1->GetYaxis()->SetLabelOffset(ylboffset1x1);

    cos_trackp1_trackm1->SetTitle("");
    cos_trackp1_trackm1->SetStats(0);
    cos_trackp1_trackm1->SetXTitle("<cos(#Psi_{1}{track+} - #Psi_{1}{track-})>");
    cos_trackp1_trackm1->SetYTitle("");
    cos_trackp1_trackm1->GetXaxis()->CenterTitle(kTRUE);
    cos_trackp1_trackm1->GetYaxis()->CenterTitle(kTRUE);
    cos_trackp1_trackm1->GetXaxis()->SetTitleSize(xtlsize1x1);
    cos_trackp1_trackm1->GetYaxis()->SetTitleSize(ytlsize1x1);
    cos_trackp1_trackm1->GetXaxis()->SetTitleOffset(xtloffset1x1);
    cos_trackp1_trackm1->GetYaxis()->SetTitleOffset(ytloffset1x1);
    cos_trackp1_trackm1->GetXaxis()->SetLabelSize(xlbsize1x1);
    cos_trackp1_trackm1->GetYaxis()->SetLabelSize(ylbsize1x1);
    cos_trackp1_trackm1->GetXaxis()->SetLabelOffset(xlboffset1x1);
    cos_trackp1_trackm1->GetYaxis()->SetLabelOffset(ylboffset1x1);

    cos_trackp1_HFp1->SetTitle("");
    cos_trackp1_HFp1->SetStats(0);
    cos_trackp1_HFp1->SetXTitle("<cos(#Psi_{1}{track+} - #Psi_{1}{HF+})>");
    cos_trackp1_HFp1->SetYTitle("");
    cos_trackp1_HFp1->GetXaxis()->CenterTitle(kTRUE);
    cos_trackp1_HFp1->GetYaxis()->CenterTitle(kTRUE);
    cos_trackp1_HFp1->GetXaxis()->SetTitleSize(xtlsize1x1);
    cos_trackp1_HFp1->GetYaxis()->SetTitleSize(ytlsize1x1);
    cos_trackp1_HFp1->GetXaxis()->SetTitleOffset(xtloffset1x1);
    cos_trackp1_HFp1->GetYaxis()->SetTitleOffset(ytloffset1x1);
    cos_trackp1_HFp1->GetXaxis()->SetLabelSize(xlbsize1x1);
    cos_trackp1_HFp1->GetYaxis()->SetLabelSize(ylbsize1x1);
    cos_trackp1_HFp1->GetXaxis()->SetLabelOffset(xlboffset1x1);
    cos_trackp1_HFp1->GetYaxis()->SetLabelOffset(ylboffset1x1);


    cos_HFm1_trackm2->SetTitle("");
    cos_HFm1_trackm2->SetStats(0);
    cos_HFm1_trackm2->SetXTitle("<cos(#Psi_{1}{HF-} - #Psi_{2}{track-})>");
    cos_HFm1_trackm2->SetYTitle("");
    cos_HFm1_trackm2->GetXaxis()->CenterTitle(kTRUE);
    cos_HFm1_trackm2->GetYaxis()->CenterTitle(kTRUE);
    cos_HFm1_trackm2->GetXaxis()->SetTitleSize(xtlsize1x1);
    cos_HFm1_trackm2->GetYaxis()->SetTitleSize(ytlsize1x1);
    cos_HFm1_trackm2->GetXaxis()->SetTitleOffset(xtloffset1x1);
    cos_HFm1_trackm2->GetYaxis()->SetTitleOffset(ytloffset1x1);
    cos_HFm1_trackm2->GetXaxis()->SetLabelSize(xlbsize1x1);
    cos_HFm1_trackm2->GetYaxis()->SetLabelSize(ylbsize1x1);
    cos_HFm1_trackm2->GetXaxis()->SetLabelOffset(xlboffset1x1);
    cos_HFm1_trackm2->GetYaxis()->SetLabelOffset(ylboffset1x1);

    cos_HFm1_trackp2->SetTitle("");
    cos_HFm1_trackp2->SetStats(0);
    cos_HFm1_trackp2->SetXTitle("<cos(#Psi_{1}{HF-} - #Psi_{2}{track+})>");
    cos_HFm1_trackp2->SetYTitle("");
    cos_HFm1_trackp2->GetXaxis()->CenterTitle(kTRUE);
    cos_HFm1_trackp2->GetYaxis()->CenterTitle(kTRUE);
    cos_HFm1_trackp2->GetXaxis()->SetTitleSize(xtlsize1x1);
    cos_HFm1_trackp2->GetYaxis()->SetTitleSize(ytlsize1x1);
    cos_HFm1_trackp2->GetXaxis()->SetTitleOffset(xtloffset1x1);
    cos_HFm1_trackp2->GetYaxis()->SetTitleOffset(ytloffset1x1);
    cos_HFm1_trackp2->GetXaxis()->SetLabelSize(xlbsize1x1);
    cos_HFm1_trackp2->GetYaxis()->SetLabelSize(ylbsize1x1);
    cos_HFm1_trackp2->GetXaxis()->SetLabelOffset(xlboffset1x1);
    cos_HFm1_trackp2->GetYaxis()->SetLabelOffset(ylboffset1x1);

    cos_HFp1_trackm2->SetTitle("");
    cos_HFp1_trackm2->SetStats(0);
    cos_HFp1_trackm2->SetXTitle("<cos(#Psi_{1}{HF+} - #Psi_{2}{track-})>");
    cos_HFp1_trackm2->SetYTitle("");
    cos_HFp1_trackm2->GetXaxis()->CenterTitle(kTRUE);
    cos_HFp1_trackm2->GetYaxis()->CenterTitle(kTRUE);
    cos_HFp1_trackm2->GetXaxis()->SetTitleSize(xtlsize1x1);
    cos_HFp1_trackm2->GetYaxis()->SetTitleSize(ytlsize1x1);
    cos_HFp1_trackm2->GetXaxis()->SetTitleOffset(xtloffset1x1);
    cos_HFp1_trackm2->GetYaxis()->SetTitleOffset(ytloffset1x1);
    cos_HFp1_trackm2->GetXaxis()->SetLabelSize(xlbsize1x1);
    cos_HFp1_trackm2->GetYaxis()->SetLabelSize(ylbsize1x1);
    cos_HFp1_trackm2->GetXaxis()->SetLabelOffset(xlboffset1x1);
    cos_HFp1_trackm2->GetYaxis()->SetLabelOffset(ylboffset1x1);

    cos_HFp1_trackp2->SetTitle("");
    cos_HFp1_trackp2->SetStats(0);
    cos_HFp1_trackp2->SetXTitle("<cos(#Psi_{1}{HF+} - #Psi_{2}{track+})>");
    cos_HFp1_trackp2->SetYTitle("");
    cos_HFp1_trackp2->GetXaxis()->CenterTitle(kTRUE);
    cos_HFp1_trackp2->GetYaxis()->CenterTitle(kTRUE);
    cos_HFp1_trackp2->GetXaxis()->SetTitleSize(xtlsize1x1);
    cos_HFp1_trackp2->GetYaxis()->SetTitleSize(ytlsize1x1);
    cos_HFp1_trackp2->GetXaxis()->SetTitleOffset(xtloffset1x1);
    cos_HFp1_trackp2->GetYaxis()->SetTitleOffset(ytloffset1x1);
    cos_HFp1_trackp2->GetXaxis()->SetLabelSize(xlbsize1x1);
    cos_HFp1_trackp2->GetYaxis()->SetLabelSize(ylbsize1x1);
    cos_HFp1_trackp2->GetXaxis()->SetLabelOffset(xlboffset1x1);
    cos_HFp1_trackp2->GetYaxis()->SetLabelOffset(ylboffset1x1);

    cos_HFm1_HFp2->SetTitle("");
    cos_HFm1_HFp2->SetStats(0);
    cos_HFm1_HFp2->SetXTitle("<cos(#Psi_{1}{HF-} - #Psi_{2}{HF+})>");
    cos_HFm1_HFp2->SetYTitle("");
    cos_HFm1_HFp2->GetXaxis()->CenterTitle(kTRUE);
    cos_HFm1_HFp2->GetYaxis()->CenterTitle(kTRUE);
    cos_HFm1_HFp2->GetXaxis()->SetTitleSize(xtlsize1x1);
    cos_HFm1_HFp2->GetYaxis()->SetTitleSize(ytlsize1x1);
    cos_HFm1_HFp2->GetXaxis()->SetTitleOffset(xtloffset1x1);
    cos_HFm1_HFp2->GetYaxis()->SetTitleOffset(ytloffset1x1);
    cos_HFm1_HFp2->GetXaxis()->SetLabelSize(xlbsize1x1);
    cos_HFm1_HFp2->GetYaxis()->SetLabelSize(ylbsize1x1);
    cos_HFm1_HFp2->GetXaxis()->SetLabelOffset(xlboffset1x1);
    cos_HFm1_HFp2->GetYaxis()->SetLabelOffset(ylboffset1x1);

    cos_HFp1_HFm2->SetTitle("");
    cos_HFp1_HFm2->SetStats(0);
    cos_HFp1_HFm2->SetXTitle("<cos(#Psi_{1}{HF+} - #Psi_{2}{HF-})>");
    cos_HFp1_HFm2->SetYTitle("");
    cos_HFp1_HFm2->GetXaxis()->CenterTitle(kTRUE);
    cos_HFp1_HFm2->GetYaxis()->CenterTitle(kTRUE);
    cos_HFp1_HFm2->GetXaxis()->SetTitleSize(xtlsize1x1);
    cos_HFp1_HFm2->GetYaxis()->SetTitleSize(ytlsize1x1);
    cos_HFp1_HFm2->GetXaxis()->SetTitleOffset(xtloffset1x1);
    cos_HFp1_HFm2->GetYaxis()->SetTitleOffset(ytloffset1x1);
    cos_HFp1_HFm2->GetXaxis()->SetLabelSize(xlbsize1x1);
    cos_HFp1_HFm2->GetYaxis()->SetLabelSize(ylbsize1x1);
    cos_HFp1_HFm2->GetXaxis()->SetLabelOffset(xlboffset1x1);
    cos_HFp1_HFm2->GetYaxis()->SetLabelOffset(ylboffset1x1);

    cos_trackmid1_HFm2->SetTitle("");
    cos_trackmid1_HFm2->SetStats(0);
    cos_trackmid1_HFm2->SetXTitle("<cos(#Psi_{1}{trackmid} - #Psi_{2}{HF-})>");
    cos_trackmid1_HFm2->SetYTitle("");
    cos_trackmid1_HFm2->GetXaxis()->CenterTitle(kTRUE);
    cos_trackmid1_HFm2->GetYaxis()->CenterTitle(kTRUE);
    cos_trackmid1_HFm2->GetXaxis()->SetTitleSize(xtlsize1x1);
    cos_trackmid1_HFm2->GetYaxis()->SetTitleSize(ytlsize1x1);
    cos_trackmid1_HFm2->GetXaxis()->SetTitleOffset(xtloffset1x1);
    cos_trackmid1_HFm2->GetYaxis()->SetTitleOffset(ytloffset1x1);
    cos_trackmid1_HFm2->GetXaxis()->SetLabelSize(xlbsize1x1);
    cos_trackmid1_HFm2->GetYaxis()->SetLabelSize(ylbsize1x1);
    cos_trackmid1_HFm2->GetXaxis()->SetLabelOffset(xlboffset1x1);
    cos_trackmid1_HFm2->GetYaxis()->SetLabelOffset(ylboffset1x1);

    cos_trackmid1_HFp2->SetTitle("");
    cos_trackmid1_HFp2->SetStats(0);
    cos_trackmid1_HFp2->SetXTitle("<cos(#Psi_{1}{trackmid} - #Psi_{2}{HF+})>");
    cos_trackmid1_HFp2->SetYTitle("");
    cos_trackmid1_HFp2->GetXaxis()->CenterTitle(kTRUE);
    cos_trackmid1_HFp2->GetYaxis()->CenterTitle(kTRUE);
    cos_trackmid1_HFp2->GetXaxis()->SetTitleSize(xtlsize1x1);
    cos_trackmid1_HFp2->GetYaxis()->SetTitleSize(ytlsize1x1);
    cos_trackmid1_HFp2->GetXaxis()->SetTitleOffset(xtloffset1x1);
    cos_trackmid1_HFp2->GetYaxis()->SetTitleOffset(ytloffset1x1);
    cos_trackmid1_HFp2->GetXaxis()->SetLabelSize(xlbsize1x1);
    cos_trackmid1_HFp2->GetYaxis()->SetLabelSize(ylbsize1x1);
    cos_trackmid1_HFp2->GetXaxis()->SetLabelOffset(xlboffset1x1);
    cos_trackmid1_HFp2->GetYaxis()->SetLabelOffset(ylboffset1x1);

    cos_trackm1_HFm2->SetTitle("");
    cos_trackm1_HFm2->SetStats(0);
    cos_trackm1_HFm2->SetXTitle("<cos(#Psi_{1}{track-} - #Psi_{2}{HF-})>");
    cos_trackm1_HFm2->SetYTitle("");
    cos_trackm1_HFm2->GetXaxis()->CenterTitle(kTRUE);
    cos_trackm1_HFm2->GetYaxis()->CenterTitle(kTRUE);
    cos_trackm1_HFm2->GetXaxis()->SetTitleSize(xtlsize1x1);
    cos_trackm1_HFm2->GetYaxis()->SetTitleSize(ytlsize1x1);
    cos_trackm1_HFm2->GetXaxis()->SetTitleOffset(xtloffset1x1);
    cos_trackm1_HFm2->GetYaxis()->SetTitleOffset(ytloffset1x1);
    cos_trackm1_HFm2->GetXaxis()->SetLabelSize(xlbsize1x1);
    cos_trackm1_HFm2->GetYaxis()->SetLabelSize(ylbsize1x1);
    cos_trackm1_HFm2->GetXaxis()->SetLabelOffset(xlboffset1x1);
    cos_trackm1_HFm2->GetYaxis()->SetLabelOffset(ylboffset1x1);

    cos_trackm1_trackp2->SetTitle("");
    cos_trackm1_trackp2->SetStats(0);
    cos_trackm1_trackp2->SetXTitle("<cos(#Psi_{1}{track-} - #Psi_{2}{track+})>");
    cos_trackm1_trackp2->SetYTitle("");
    cos_trackm1_trackp2->GetXaxis()->CenterTitle(kTRUE);
    cos_trackm1_trackp2->GetYaxis()->CenterTitle(kTRUE);
    cos_trackm1_trackp2->GetXaxis()->SetTitleSize(xtlsize1x1);
    cos_trackm1_trackp2->GetYaxis()->SetTitleSize(ytlsize1x1);
    cos_trackm1_trackp2->GetXaxis()->SetTitleOffset(xtloffset1x1);
    cos_trackm1_trackp2->GetYaxis()->SetTitleOffset(ytloffset1x1);
    cos_trackm1_trackp2->GetXaxis()->SetLabelSize(xlbsize1x1);
    cos_trackm1_trackp2->GetYaxis()->SetLabelSize(ylbsize1x1);
    cos_trackm1_trackp2->GetXaxis()->SetLabelOffset(xlboffset1x1);
    cos_trackm1_trackp2->GetYaxis()->SetLabelOffset(ylboffset1x1);

    cos_trackm1_HFp2->SetTitle("");
    cos_trackm1_HFp2->SetStats(0);
    cos_trackm1_HFp2->SetXTitle("<cos(#Psi_{1}{track-} - #Psi_{2}{HF+})>");
    cos_trackm1_HFp2->SetYTitle("");
    cos_trackm1_HFp2->GetXaxis()->CenterTitle(kTRUE);
    cos_trackm1_HFp2->GetYaxis()->CenterTitle(kTRUE);
    cos_trackm1_HFp2->GetXaxis()->SetTitleSize(xtlsize1x1);
    cos_trackm1_HFp2->GetYaxis()->SetTitleSize(ytlsize1x1);
    cos_trackm1_HFp2->GetXaxis()->SetTitleOffset(xtloffset1x1);
    cos_trackm1_HFp2->GetYaxis()->SetTitleOffset(ytloffset1x1);
    cos_trackm1_HFp2->GetXaxis()->SetLabelSize(xlbsize1x1);
    cos_trackm1_HFp2->GetYaxis()->SetLabelSize(ylbsize1x1);
    cos_trackm1_HFp2->GetXaxis()->SetLabelOffset(xlboffset1x1);
    cos_trackm1_HFp2->GetYaxis()->SetLabelOffset(ylboffset1x1);

    cos_trackp1_HFm2->SetTitle("");
    cos_trackp1_HFm2->SetStats(0);
    cos_trackp1_HFm2->SetXTitle("<cos(#Psi_{1}{track+} - #Psi_{2}{HF-})>");
    cos_trackp1_HFm2->SetYTitle("");
    cos_trackp1_HFm2->GetXaxis()->CenterTitle(kTRUE);
    cos_trackp1_HFm2->GetYaxis()->CenterTitle(kTRUE);
    cos_trackp1_HFm2->GetXaxis()->SetTitleSize(xtlsize1x1);
    cos_trackp1_HFm2->GetYaxis()->SetTitleSize(ytlsize1x1);
    cos_trackp1_HFm2->GetXaxis()->SetTitleOffset(xtloffset1x1);
    cos_trackp1_HFm2->GetYaxis()->SetTitleOffset(ytloffset1x1);
    cos_trackp1_HFm2->GetXaxis()->SetLabelSize(xlbsize1x1);
    cos_trackp1_HFm2->GetYaxis()->SetLabelSize(ylbsize1x1);
    cos_trackp1_HFm2->GetXaxis()->SetLabelOffset(xlboffset1x1);
    cos_trackp1_HFm2->GetYaxis()->SetLabelOffset(ylboffset1x1);

    cos_trackp1_trackm2->SetTitle("");
    cos_trackp1_trackm2->SetStats(0);
    cos_trackp1_trackm2->SetXTitle("<cos(#Psi_{1}{track+} - #Psi_{2}{track-})>");
    cos_trackp1_trackm2->SetYTitle("");
    cos_trackp1_trackm2->GetXaxis()->CenterTitle(kTRUE);
    cos_trackp1_trackm2->GetYaxis()->CenterTitle(kTRUE);
    cos_trackp1_trackm2->GetXaxis()->SetTitleSize(xtlsize1x1);
    cos_trackp1_trackm2->GetYaxis()->SetTitleSize(ytlsize1x1);
    cos_trackp1_trackm2->GetXaxis()->SetTitleOffset(xtloffset1x1);
    cos_trackp1_trackm2->GetYaxis()->SetTitleOffset(ytloffset1x1);
    cos_trackp1_trackm2->GetXaxis()->SetLabelSize(xlbsize1x1);
    cos_trackp1_trackm2->GetYaxis()->SetLabelSize(ylbsize1x1);
    cos_trackp1_trackm2->GetXaxis()->SetLabelOffset(xlboffset1x1);
    cos_trackp1_trackm2->GetYaxis()->SetLabelOffset(ylboffset1x1);

    cos_trackp1_HFp2->SetTitle("");
    cos_trackp1_HFp2->SetStats(0);
    cos_trackp1_HFp2->SetXTitle("<cos(#Psi_{1}{track+} - #Psi_{2}{HF+})>");
    cos_trackp1_HFp2->SetYTitle("");
    cos_trackp1_HFp2->GetXaxis()->CenterTitle(kTRUE);
    cos_trackp1_HFp2->GetYaxis()->CenterTitle(kTRUE);
    cos_trackp1_HFp2->GetXaxis()->SetTitleSize(xtlsize1x1);
    cos_trackp1_HFp2->GetYaxis()->SetTitleSize(ytlsize1x1);
    cos_trackp1_HFp2->GetXaxis()->SetTitleOffset(xtloffset1x1);
    cos_trackp1_HFp2->GetYaxis()->SetTitleOffset(ytloffset1x1);
    cos_trackp1_HFp2->GetXaxis()->SetLabelSize(xlbsize1x1);
    cos_trackp1_HFp2->GetYaxis()->SetLabelSize(ylbsize1x1);
    cos_trackp1_HFp2->GetXaxis()->SetLabelOffset(xlboffset1x1);
    cos_trackp1_HFp2->GetYaxis()->SetLabelOffset(ylboffset1x1);


    cos_HFm2_HFp2->SetTitle("");
    cos_HFm2_HFp2->SetStats(0);
    cos_HFm2_HFp2->SetXTitle("<cos(#Psi_{2}{HF-} - #Psi_{2}{HF+})>");
    cos_HFm2_HFp2->SetYTitle("");
    cos_HFm2_HFp2->GetXaxis()->CenterTitle(kTRUE);
    cos_HFm2_HFp2->GetYaxis()->CenterTitle(kTRUE);
    cos_HFm2_HFp2->GetXaxis()->SetTitleSize(xtlsize1x1);
    cos_HFm2_HFp2->GetYaxis()->SetTitleSize(ytlsize1x1);
    cos_HFm2_HFp2->GetXaxis()->SetTitleOffset(xtloffset1x1);
    cos_HFm2_HFp2->GetYaxis()->SetTitleOffset(ytloffset1x1);
    cos_HFm2_HFp2->GetXaxis()->SetLabelSize(xlbsize1x1);
    cos_HFm2_HFp2->GetYaxis()->SetLabelSize(ylbsize1x1);
    cos_HFm2_HFp2->GetXaxis()->SetLabelOffset(xlboffset1x1);
    cos_HFm2_HFp2->GetYaxis()->SetLabelOffset(ylboffset1x1);

    cos_trackmid2_HFm2->SetTitle("");
    cos_trackmid2_HFm2->SetStats(0);
    cos_trackmid2_HFm2->SetXTitle("<cos(#Psi_{2}{trackmid} - #Psi_{2}{HF-})>");
    cos_trackmid2_HFm2->SetYTitle("");
    cos_trackmid2_HFm2->GetXaxis()->CenterTitle(kTRUE);
    cos_trackmid2_HFm2->GetYaxis()->CenterTitle(kTRUE);
    cos_trackmid2_HFm2->GetXaxis()->SetTitleSize(xtlsize1x1);
    cos_trackmid2_HFm2->GetYaxis()->SetTitleSize(ytlsize1x1);
    cos_trackmid2_HFm2->GetXaxis()->SetTitleOffset(xtloffset1x1);
    cos_trackmid2_HFm2->GetYaxis()->SetTitleOffset(ytloffset1x1);
    cos_trackmid2_HFm2->GetXaxis()->SetLabelSize(xlbsize1x1);
    cos_trackmid2_HFm2->GetYaxis()->SetLabelSize(ylbsize1x1);
    cos_trackmid2_HFm2->GetXaxis()->SetLabelOffset(xlboffset1x1);
    cos_trackmid2_HFm2->GetYaxis()->SetLabelOffset(ylboffset1x1);

    cos_trackmid2_HFp2->SetTitle("");
    cos_trackmid2_HFp2->SetStats(0);
    cos_trackmid2_HFp2->SetXTitle("<cos(#Psi_{2}{trackmid} - #Psi_{2}{HF+})>");
    cos_trackmid2_HFp2->SetYTitle("");
    cos_trackmid2_HFp2->GetXaxis()->CenterTitle(kTRUE);
    cos_trackmid2_HFp2->GetYaxis()->CenterTitle(kTRUE);
    cos_trackmid2_HFp2->GetXaxis()->SetTitleSize(xtlsize1x1);
    cos_trackmid2_HFp2->GetYaxis()->SetTitleSize(ytlsize1x1);
    cos_trackmid2_HFp2->GetXaxis()->SetTitleOffset(xtloffset1x1);
    cos_trackmid2_HFp2->GetYaxis()->SetTitleOffset(ytloffset1x1);
    cos_trackmid2_HFp2->GetXaxis()->SetLabelSize(xlbsize1x1);
    cos_trackmid2_HFp2->GetYaxis()->SetLabelSize(ylbsize1x1);
    cos_trackmid2_HFp2->GetXaxis()->SetLabelOffset(xlboffset1x1);
    cos_trackmid2_HFp2->GetYaxis()->SetLabelOffset(ylboffset1x1);

    cos_trackm2_HFm2->SetTitle("");
    cos_trackm2_HFm2->SetStats(0);
    cos_trackm2_HFm2->SetXTitle("<cos(#Psi_{2}{track-} - #Psi_{2}{HF-})>");
    cos_trackm2_HFm2->SetYTitle("");
    cos_trackm2_HFm2->GetXaxis()->CenterTitle(kTRUE);
    cos_trackm2_HFm2->GetYaxis()->CenterTitle(kTRUE);
    cos_trackm2_HFm2->GetXaxis()->SetTitleSize(xtlsize1x1);
    cos_trackm2_HFm2->GetYaxis()->SetTitleSize(ytlsize1x1);
    cos_trackm2_HFm2->GetXaxis()->SetTitleOffset(xtloffset1x1);
    cos_trackm2_HFm2->GetYaxis()->SetTitleOffset(ytloffset1x1);
    cos_trackm2_HFm2->GetXaxis()->SetLabelSize(xlbsize1x1);
    cos_trackm2_HFm2->GetYaxis()->SetLabelSize(ylbsize1x1);
    cos_trackm2_HFm2->GetXaxis()->SetLabelOffset(xlboffset1x1);
    cos_trackm2_HFm2->GetYaxis()->SetLabelOffset(ylboffset1x1);

    cos_trackm2_trackp2->SetTitle("");
    cos_trackm2_trackp2->SetStats(0);
    cos_trackm2_trackp2->SetXTitle("<cos(#Psi_{2}{track-} - #Psi_{2}{track+})>");
    cos_trackm2_trackp2->SetYTitle("");
    cos_trackm2_trackp2->GetXaxis()->CenterTitle(kTRUE);
    cos_trackm2_trackp2->GetYaxis()->CenterTitle(kTRUE);
    cos_trackm2_trackp2->GetXaxis()->SetTitleSize(xtlsize1x1);
    cos_trackm2_trackp2->GetYaxis()->SetTitleSize(ytlsize1x1);
    cos_trackm2_trackp2->GetXaxis()->SetTitleOffset(xtloffset1x1);
    cos_trackm2_trackp2->GetYaxis()->SetTitleOffset(ytloffset1x1);
    cos_trackm2_trackp2->GetXaxis()->SetLabelSize(xlbsize1x1);
    cos_trackm2_trackp2->GetYaxis()->SetLabelSize(ylbsize1x1);
    cos_trackm2_trackp2->GetXaxis()->SetLabelOffset(xlboffset1x1);
    cos_trackm2_trackp2->GetYaxis()->SetLabelOffset(ylboffset1x1);

    cos_trackm2_HFp2->SetTitle("");
    cos_trackm2_HFp2->SetStats(0);
    cos_trackm2_HFp2->SetXTitle("<cos(#Psi_{2}{track-} - #Psi_{2}{HF+})>");
    cos_trackm2_HFp2->SetYTitle("");
    cos_trackm2_HFp2->GetXaxis()->CenterTitle(kTRUE);
    cos_trackm2_HFp2->GetYaxis()->CenterTitle(kTRUE);
    cos_trackm2_HFp2->GetXaxis()->SetTitleSize(xtlsize1x1);
    cos_trackm2_HFp2->GetYaxis()->SetTitleSize(ytlsize1x1);
    cos_trackm2_HFp2->GetXaxis()->SetTitleOffset(xtloffset1x1);
    cos_trackm2_HFp2->GetYaxis()->SetTitleOffset(ytloffset1x1);
    cos_trackm2_HFp2->GetXaxis()->SetLabelSize(xlbsize1x1);
    cos_trackm2_HFp2->GetYaxis()->SetLabelSize(ylbsize1x1);
    cos_trackm2_HFp2->GetXaxis()->SetLabelOffset(xlboffset1x1);
    cos_trackm2_HFp2->GetYaxis()->SetLabelOffset(ylboffset1x1);

    cos_trackp2_HFm2->SetTitle("");
    cos_trackp2_HFm2->SetStats(0);
    cos_trackp2_HFm2->SetXTitle("<cos(#Psi_{2}{track+} - #Psi_{2}{HF-})>");
    cos_trackp2_HFm2->SetYTitle("");
    cos_trackp2_HFm2->GetXaxis()->CenterTitle(kTRUE);
    cos_trackp2_HFm2->GetYaxis()->CenterTitle(kTRUE);
    cos_trackp2_HFm2->GetXaxis()->SetTitleSize(xtlsize1x1);
    cos_trackp2_HFm2->GetYaxis()->SetTitleSize(ytlsize1x1);
    cos_trackp2_HFm2->GetXaxis()->SetTitleOffset(xtloffset1x1);
    cos_trackp2_HFm2->GetYaxis()->SetTitleOffset(ytloffset1x1);
    cos_trackp2_HFm2->GetXaxis()->SetLabelSize(xlbsize1x1);
    cos_trackp2_HFm2->GetYaxis()->SetLabelSize(ylbsize1x1);
    cos_trackp2_HFm2->GetXaxis()->SetLabelOffset(xlboffset1x1);
    cos_trackp2_HFm2->GetYaxis()->SetLabelOffset(ylboffset1x1);

    cos_trackp2_HFp2->SetTitle("");
    cos_trackp2_HFp2->SetStats(0);
    cos_trackp2_HFp2->SetXTitle("<cos(#Psi_{2}{track+} - #Psi_{2}{HF+})>");
    cos_trackp2_HFp2->SetYTitle("");
    cos_trackp2_HFp2->GetXaxis()->CenterTitle(kTRUE);
    cos_trackp2_HFp2->GetYaxis()->CenterTitle(kTRUE);
    cos_trackp2_HFp2->GetXaxis()->SetTitleSize(xtlsize1x1);
    cos_trackp2_HFp2->GetYaxis()->SetTitleSize(ytlsize1x1);
    cos_trackp2_HFp2->GetXaxis()->SetTitleOffset(xtloffset1x1);
    cos_trackp2_HFp2->GetYaxis()->SetTitleOffset(ytloffset1x1);
    cos_trackp2_HFp2->GetXaxis()->SetLabelSize(xlbsize1x1);
    cos_trackp2_HFp2->GetYaxis()->SetLabelSize(ylbsize1x1);
    cos_trackp2_HFp2->GetXaxis()->SetLabelOffset(xlboffset1x1);
    cos_trackp2_HFp2->GetYaxis()->SetLabelOffset(ylboffset1x1);

}
